// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type APIStandard struct {
	APIStandardHandle string           `db:"api_standard_handle" json:"api_standard_handle"`
	Description       pgtype.Text      `db:"description" json:"description"`
	KeyMethod         string           `db:"key_method" json:"key_method"`
	KeyField          pgtype.Text      `db:"key_field" json:"key_field"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Definition struct {
	DefinitionID     int32            `db:"definition_id" json:"definition_id"`
	DefinitionHandle string           `db:"definition_handle" json:"definition_handle"`
	Owner            string           `db:"owner" json:"owner"`
	Endpoint         string           `db:"endpoint" json:"endpoint"`
	Description      pgtype.Text      `db:"description" json:"description"`
	APIStandard      string           `db:"api_standard" json:"api_standard"`
	Model            string           `db:"model" json:"model"`
	Dimensions       pgtype.Int4      `db:"dimensions" json:"dimensions"`
	ContextLimit     pgtype.Int4      `db:"context_limit" json:"context_limit"`
	IsPublic         bool             `db:"is_public" json:"is_public"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type DefinitionsSharedWith struct {
	UserHandle   string           `db:"user_handle" json:"user_handle"`
	DefinitionID int32            `db:"definition_id" json:"definition_id"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Embedding struct {
	EmbeddingsID int32                  `db:"embeddings_id" json:"embeddings_id"`
	TextID       pgtype.Text            `db:"text_id" json:"text_id"`
	Owner        string                 `db:"owner" json:"owner"`
	ProjectID    int32                  `db:"project_id" json:"project_id"`
	InstanceID   int32                  `db:"instance_id" json:"instance_id"`
	Text         pgtype.Text            `db:"text" json:"text"`
	Vector       pgvector_go.HalfVector `db:"vector" json:"vector"`
	VectorDim    int32                  `db:"vector_dim" json:"vector_dim"`
	Metadata     []byte                 `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

type Instance struct {
	InstanceID      int32            `db:"instance_id" json:"instance_id"`
	InstanceHandle  string           `db:"instance_handle" json:"instance_handle"`
	Owner           string           `db:"owner" json:"owner"`
	Endpoint        string           `db:"endpoint" json:"endpoint"`
	Description     pgtype.Text      `db:"description" json:"description"`
	APIStandard     string           `db:"api_standard" json:"api_standard"`
	Model           string           `db:"model" json:"model"`
	Dimensions      pgtype.Int4      `db:"dimensions" json:"dimensions"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ContextLimit    pgtype.Int4      `db:"context_limit" json:"context_limit"`
	DefinitionID    pgtype.Int4      `db:"definition_id" json:"definition_id"`
	APIKeyEncrypted []byte           `db:"api_key_encrypted" json:"api_key_encrypted"`
}

type InstancesSharedWith struct {
	UserHandle string           `db:"user_handle" json:"user_handle"`
	InstanceID int32            `db:"instance_id" json:"instance_id"`
	Role       string           `db:"role" json:"role"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type KeyMethod struct {
	KeyMethod string `db:"key_method" json:"key_method"`
}

type Project struct {
	ProjectID      int32            `db:"project_id" json:"project_id"`
	ProjectHandle  string           `db:"project_handle" json:"project_handle"`
	Owner          string           `db:"owner" json:"owner"`
	Description    pgtype.Text      `db:"description" json:"description"`
	MetadataScheme pgtype.Text      `db:"metadata_scheme" json:"metadata_scheme"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	PublicRead     pgtype.Bool      `db:"public_read" json:"public_read"`
	InstanceID     pgtype.Int4      `db:"instance_id" json:"instance_id"`
}

type User struct {
	UserHandle string           `db:"user_handle" json:"user_handle"`
	Name       pgtype.Text      `db:"name" json:"name"`
	Email      string           `db:"email" json:"email"`
	EmbAPIKey  string           `db:"vdb_key" json:"vdb_key"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type UsersProject struct {
	UserHandle string           `db:"user_handle" json:"user_handle"`
	ProjectID  int32            `db:"project_id" json:"project_id"`
	Role       string           `db:"role" json:"role"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type VdbRole struct {
	VdbRole string `db:"vdb_role" json:"vdb_role"`
}
