baseURL = 'https://mpilhlt.github.io/embapi/'
languageCode = 'en-us'
title = 'EmbAPI Documentation'
theme = 'book'

[params]
  BookRepo = 'https://github.com/mpilhlt/embapi'
  BookEditPath = 'edit/main'
  BookSearch = true
